# Server Configuration
server:
  port: 5000
  error:
    include-stacktrace: always
  compression:
    enabled: true
#  address: 0.0.0.0



# Spring Configuration
spring:
  application:
    name: one2one-service

  # Database Configuration
  datasource:
    #live
    url: jdbc:mysql://aws.ciyidojun6nb.us-east-2.rds.amazonaws.com:3306/awsdemo
    username: admin
    password: nbr12345

    #local
#    url: jdbc:mysql://localhost:3306/one2one
#    username: root
#    password: root


    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    # Properties
    properties:
      # Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true

    # Hibernate
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: false

#  # Redis Configuration
#  redis:
#    host: 192.168.1.17
#    port: 6379
#    connect-timeout: 21600


# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"

#ftpFileUploadPath: /one2one-service

#redis:
#  host: 192.168.1.17
#  port: 6379
